DELETE http://localhost:3001/api/blogs/66cf599ccc144925d84f3551
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QyIiwiaWQiOiI2NmNmNTgyZWVhNzkyMzhlOTk5NTM4MmUiLCJpYXQiOjE3MjQ4NjU1ODUsImV4cCI6MTcyNDg2NTYxNX0.jEF31eALi_AluOb4GXDbTEIVjSD37MELjkGXj_gwGoM